In [ ]:
# Data Exploration

In [2]:
import pandas as pd
pd.options.display.max_columns =None
pd.options.display.max_rows =40


filename = 'file:///Users/divyajagarlapoodi/Desktop/Breast%20Cancer%20DataSet%20.csv'
    
df = pd.read_csv(filename)

In [3]:
#start of by actually looking at your data set
df

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1.0,benign,Dr. Doe
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1.0,benign,Dr. Smith
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1.0,benign,Dr. Lee
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1.0,benign,Dr. Smith
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1.0,benign,Dr. Wong
...,...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3.0,1.0,1,1,3,2,1.0,1.0,1.0,benign,Dr. Lee
695,841769,2.0,1.0,1,1,2,1,1.0,1.0,1.0,benign,Dr. Smith
696,888820,5.0,10.0,10,3,7,3,8.0,10.0,2.0,malignant,Dr. Lee
697,897471,4.0,8.0,6,4,3,4,10.0,6.0,1.0,malignant,Dr. Lee
698,897471,4.0,8.0,8,5,4,5,10.0,4.0,1.0,malignant,Dr. Wong

In [4]:
# What is the size of our dataset?
df.shape

(699, 12)

In [5]:
# Over here we see the columns names and their data types
df.dtypes

patient_id                 int64
clump_thickness          float64
cell_size_uniformity     float64
cell_shape_uniformity      int64
marginal_adhesion          int64
single_ep_cell_size        int64
bare_nuclei               object
bland_chromatin          float64
normal_nucleoli          float64
mitoses                  float64
class                     object
doctor_name               object
dtype: object

In [6]:
#Its good to inspect your unique key identifier
df.nunique()

patient_id               645
clump_thickness           10
cell_size_uniformity      10
cell_shape_uniformity     10
marginal_adhesion         10
single_ep_cell_size       10
bare_nuclei               11
bland_chromatin           10
normal_nucleoli           10
mitoses                    9
class                      2
doctor_name                4
dtype: int64

In [7]:
# Here we list all columns
df.columns

Index(['patient_id', 'clump_thickness', 'cell_size_uniformity',
       'cell_shape_uniformity', 'marginal_adhesion', 'single_ep_cell_size',
       'bare_nuclei', 'bland_chromatin', 'normal_nucleoli', 'mitoses', 'class',
       'doctor_name'],
      dtype='object')

In [8]:
# This provides some statistics on the numerical data
df.describe()

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bland_chromatin,normal_nucleoli,mitoses
count,6.990000e+02,698.000000,698.000000,699.000000,699.000000,699.000000,695.000000,697.000000,698.000000
mean,1.071704e+06,4.416905,3.137536,3.207439,2.793991,3.216023,3.447482,2.857963,1.590258
std,6.170957e+05,2.817673,3.052575,2.971913,2.843163,2.214300,2.441191,3.045851,1.716162
min,6.163400e+04,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,8.706885e+05,2.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000
50%,1.171710e+06,4.000000,1.000000,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000
75%,1.238298e+06,6.000000,5.000000,5.000000,3.500000,4.000000,5.000000,4.000000,1.000000
max,1.345435e+07,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [9]:
# This aggreates the data by its column names, then we pass the aggregation function (size = count)
df.groupby(by =['class', 'doctor_name']).size()

class      doctor_name
benign     Dr. Doe        127
           Dr. Lee        121
           Dr. Smith      102
           Dr. Wong       108
malignant  Dr. Doe         58
           Dr. Lee         60
           Dr. Smith       73
           Dr. Wong        49
dtype: int64

In [10]:
#Dealing with missing values? How many np.nan per column?

df.isna().sum()

patient_id               0
clump_thickness          1
cell_size_uniformity     1
cell_shape_uniformity    0
marginal_adhesion        0
single_ep_cell_size      0
bare_nuclei              2
bland_chromatin          4
normal_nucleoli          2
mitoses                  1
class                    1
doctor_name              1
dtype: int64

In [11]:
df = df.dropna(axis = 1, how = 'all')  #drop rows with any column having np.nan values

#Rename columns
df.rename(index =str, columns = {'patient_id':'patient_id'})

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1.0,benign,Dr. Doe
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1.0,benign,Dr. Smith
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1.0,benign,Dr. Lee
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1.0,benign,Dr. Smith
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1.0,benign,Dr. Wong
...,...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3.0,1.0,1,1,3,2,1.0,1.0,1.0,benign,Dr. Lee
695,841769,2.0,1.0,1,1,2,1,1.0,1.0,1.0,benign,Dr. Smith
696,888820,5.0,10.0,10,3,7,3,8.0,10.0,2.0,malignant,Dr. Lee
697,897471,4.0,8.0,6,4,3,4,10.0,6.0,1.0,malignant,Dr. Lee
698,897471,4.0,8.0,8,5,4,5,10.0,4.0,1.0,malignant,Dr. Wong

In [12]:
# Its good to inspect unique key identifiers
df.nunique()

patient_id               645
clump_thickness           10
cell_size_uniformity      10
cell_shape_uniformity     10
marginal_adhesion         10
single_ep_cell_size       10
bare_nuclei               11
bland_chromatin           10
normal_nucleoli           10
mitoses                    9
class                      2
doctor_name                4
dtype: int64

In [13]:
# This shows rows that show up more than once and have the exact same column values. 
df[df.duplicated(keep = 'last')]

# # This shows all instances where pantient_id shows up more than once, but may have varying column values
# df[df.duplicated(subset = 'patient_id', keep =False)].sort_values('patient_id')

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name
168,1198641,3.0,1.0,1,1,2,1,3.0,1.0,1.0,benign,Dr. Lee

In [14]:
#Now that I have seen that there are some duplicates, I am going to go ahead and remove any duplicate rows
#, same things that occours twice

df = df.drop_duplicates(subset = None, keep ='first')

In [15]:
repeat_patients = df.groupby(by = 'patient_id').size().sort_values(ascending =False)
repeat_patients

patient_id
1182404    6
1276091    5
1105524    2
1299596    2
385103     2
          ..
1212232    1
1211594    1
1211265    1
1211202    1
61634      1
Length: 645, dtype: int64

In [16]:
# How to reverse conditionality?
print(1==1)
print(~1==1)

True
False

In [17]:
filtered_patients = repeat_patients[repeat_patients > 2].to_frame().reset_index()
filtered_df = df[~df.patient_id.isin(filtered_patients.patient_id)]
filtered_df

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1.0,benign,Dr. Doe
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1.0,benign,Dr. Smith
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1.0,benign,Dr. Lee
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1.0,benign,Dr. Smith
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1.0,benign,Dr. Wong
...,...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3.0,1.0,1,1,3,2,1.0,1.0,1.0,benign,Dr. Lee
695,841769,2.0,1.0,1,1,2,1,1.0,1.0,1.0,benign,Dr. Smith
696,888820,5.0,10.0,10,3,7,3,8.0,10.0,2.0,malignant,Dr. Lee
697,897471,4.0,8.0,6,4,3,4,10.0,6.0,1.0,malignant,Dr. Lee
698,897471,4.0,8.0,8,5,4,5,10.0,4.0,1.0,malignant,Dr. Wong

In [18]:
# This is all the repeating patients details

df[df.patient_id.isin(filtered_patients.patient_id)]

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name
136,1182404,4.0,1.0,1,1,2,1,2.0,1.0,1.0,benign,Dr. Lee
241,1276091,3.0,1.0,1,3,1,1,3.0,1.0,1.0,benign,Dr. Wong
256,1182404,3.0,1.0,1,1,2,1,1.0,1.0,1.0,benign,Dr. Wong
257,1182404,3.0,1.0,1,1,2,1,2.0,1.0,1.0,benign,Dr. Doe
265,1182404,5.0,1.0,4,1,2,1,3.0,2.0,1.0,benign,Dr. Lee
429,1276091,2.0,1.0,1,1,2,1,2.0,1.0,1.0,benign,Dr. Doe
430,1276091,1.0,3.0,1,1,2,1,2.0,2.0,1.0,benign,Dr. Wong
431,1276091,5.0,1.0,1,3,4,1,3.0,2.0,1.0,benign,Dr. Wong
448,1182404,1.0,1.0,1,1,1,1,1.0,1.0,1.0,benign,Dr. Lee
462,1276091,6.0,1.0,1,3,2,1,1.0,1.0,1.0,benign,Dr. Lee
497,1182404,4.0,2.0,1,1,2,1,1.0,1.0,1.0,benign,Dr. Wong

In [19]:
# How to view the data by aggeregting on more than one column

df.groupby('class').agg({'cell_size_uniformity': ['min', 'max'], 'normal_nucleoli': 'mean', 'class': 'count'})

          cell_size_uniformity       normal_nucleoli class
                           min   max            mean count
class
benign                     1.0   9.0        1.289474   457
malignant                  1.0  10.0        5.845833   240

In [20]:
categorical_df = df[['patient_id', 'doctor_name']]

In [21]:
# This specifies all rows (':') and column name 'doctor_count'
categorical_df.loc[:,'doctor_count'] = 1

/Applications/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:844: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/Applications/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [22]:
categorical_df

     patient_id doctor_name  doctor_count
0       1000025     Dr. Doe             1
1       1002945   Dr. Smith             1
2       1015425     Dr. Lee             1
3       1016277   Dr. Smith             1
4       1017023    Dr. Wong             1
..          ...         ...           ...
694      776715     Dr. Lee             1
695      841769   Dr. Smith             1
696      888820     Dr. Lee             1
697      897471     Dr. Lee             1
698      897471    Dr. Wong             1

[698 rows x 3 columns]

In [23]:
doctors_one_hot_encoded  = pd.pivot_table(categorical_df
                                  ,index = categorical_df.index, 
                                  columns = ['doctor_name'], values = ['doctor_count'])

In [24]:
doctors_one_hot_encoded = doctors_one_hot_encoded.fillna(0)
doctors_one_hot_encoded

            doctor_count
doctor_name      Dr. Doe Dr. Lee Dr. Smith Dr. Wong
0                    1.0     0.0       0.0      0.0
1                    0.0     0.0       1.0      0.0
2                    0.0     1.0       0.0      0.0
3                    0.0     0.0       1.0      0.0
4                    0.0     0.0       0.0      1.0
..                   ...     ...       ...      ...
694                  0.0     1.0       0.0      0.0
695                  0.0     0.0       1.0      0.0
696                  0.0     1.0       0.0      0.0
697                  0.0     1.0       0.0      0.0
698                  0.0     0.0       0.0      1.0

[697 rows x 4 columns]

In [25]:
doctors_one_hot_encoded.columns = doctors_one_hot_encoded.columns.droplevel()
doctors_one_hot_encoded

doctor_name  Dr. Doe  Dr. Lee  Dr. Smith  Dr. Wong
0                1.0      0.0        0.0       0.0
1                0.0      0.0        1.0       0.0
2                0.0      1.0        0.0       0.0
3                0.0      0.0        1.0       0.0
4                0.0      0.0        0.0       1.0
..               ...      ...        ...       ...
694              0.0      1.0        0.0       0.0
695              0.0      0.0        1.0       0.0
696              0.0      1.0        0.0       0.0
697              0.0      1.0        0.0       0.0
698              0.0      0.0        0.0       1.0

[697 rows x 4 columns]

In [26]:
combined_df = pd.merge(df, doctors_one_hot_encoded, left_index = True,right_index =True, how ='left')
combined_df

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name,Dr. Doe,Dr. Lee,Dr. Smith,Dr. Wong
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1.0,benign,Dr. Doe,1.0,0.0,0.0,0.0
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1.0,benign,Dr. Smith,0.0,0.0,1.0,0.0
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1.0,benign,Dr. Lee,0.0,1.0,0.0,0.0
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1.0,benign,Dr. Smith,0.0,0.0,1.0,0.0
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1.0,benign,Dr. Wong,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3.0,1.0,1,1,3,2,1.0,1.0,1.0,benign,Dr. Lee,0.0,1.0,0.0,0.0
695,841769,2.0,1.0,1,1,2,1,1.0,1.0,1.0,benign,Dr. Smith,0.0,0.0,1.0,0.0
696,888820,5.0,10.0,10,3,7,3,8.0,10.0,2.0,malignant,Dr. Lee,0.0,1.0,0.0,0.0
697,897471,4.0,8.0,6,4,3,4,10.0,6.0,1.0,malignant,Dr. Lee,0.0,1.0,0.0,0.0
698,897471,4.0,8.0,8,5,4,5,10.0,4.0,1.0,malignant,Dr. Wong,0.0,0.0,0.0,1.0

# Making new columns and conducting elementise operations

In [29]:
#Randomly sampling 10 rows
combined_df.sample(n=10)

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name,Dr. Doe,Dr. Lee,Dr. Smith,Dr. Wong
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1.0,benign,Dr. Wong,0.0,0.0,0.0,1.0
364,896404,2.0,1.0,1,1,2,1,3.0,1.0,1.0,benign,Dr. Doe,1.0,0.0,0.0,0.0
66,1117152,4.0,1.0,1,1,2,1,3.0,1.0,1.0,benign,Dr. Wong,0.0,0.0,0.0,1.0
693,763235,3.0,1.0,1,1,2,1,2.0,1.0,2.0,benign,Dr. Lee,0.0,1.0,0.0,0.0
212,1220330,1.0,1.0,1,1,2,1,3.0,1.0,1.0,benign,Dr. Lee,0.0,1.0,0.0,0.0
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1.0,benign,Dr. Smith,0.0,0.0,1.0,0.0
542,1174841,5.0,3.0,1,1,2,1,1.0,1.0,1.0,benign,Dr. Smith,0.0,0.0,1.0,0.0
376,640712,1.0,1.0,1,1,2,1,2.0,1.0,1.0,benign,Dr. Doe,1.0,0.0,0.0,0.0
392,1156017,3.0,1.0,1,1,2,1,2.0,1.0,1.0,benign,Dr. Wong,0.0,0.0,0.0,1.0
631,1235807,5.0,1.0,1,1,2,1,2.0,1.0,1.0,benign,Dr. Lee,0.0,1.0,0.0,0.0

In [30]:
combined_df.drop(columns=['doctor_name'])

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,Dr. Doe,Dr. Lee,Dr. Smith,Dr. Wong
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1.0,benign,1.0,0.0,0.0,0.0
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1.0,benign,0.0,0.0,1.0,0.0
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1.0,benign,0.0,1.0,0.0,0.0
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1.0,benign,0.0,0.0,1.0,0.0
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1.0,benign,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3.0,1.0,1,1,3,2,1.0,1.0,1.0,benign,0.0,1.0,0.0,0.0
695,841769,2.0,1.0,1,1,2,1,1.0,1.0,1.0,benign,0.0,0.0,1.0,0.0
696,888820,5.0,10.0,10,3,7,3,8.0,10.0,2.0,malignant,0.0,1.0,0.0,0.0
697,897471,4.0,8.0,6,4,3,4,10.0,6.0,1.0,malignant,0.0,1.0,0.0,0.0
698,897471,4.0,8.0,8,5,4,5,10.0,4.0,1.0,malignant,0.0,0.0,0.0,1.0

In [32]:
# How to convert benign & malingant to 0 and 1

class_to_numerical_dictionary = {'benign':0, 'malignant':1}

combined_df['class'] = combined_df['class'].map(class_to_numerical_dictionary)

combined_df

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name,Dr. Doe,Dr. Lee,Dr. Smith,Dr. Wong
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1.0,0.0,Dr. Doe,1.0,0.0,0.0,0.0
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1.0,0.0,Dr. Smith,0.0,0.0,1.0,0.0
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1.0,0.0,Dr. Lee,0.0,1.0,0.0,0.0
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1.0,0.0,Dr. Smith,0.0,0.0,1.0,0.0
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1.0,0.0,Dr. Wong,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3.0,1.0,1,1,3,2,1.0,1.0,1.0,0.0,Dr. Lee,0.0,1.0,0.0,0.0
695,841769,2.0,1.0,1,1,2,1,1.0,1.0,1.0,0.0,Dr. Smith,0.0,0.0,1.0,0.0
696,888820,5.0,10.0,10,3,7,3,8.0,10.0,2.0,1.0,Dr. Lee,0.0,1.0,0.0,0.0
697,897471,4.0,8.0,6,4,3,4,10.0,6.0,1.0,1.0,Dr. Lee,0.0,1.0,0.0,0.0
698,897471,4.0,8.0,8,5,4,5,10.0,4.0,1.0,1.0,Dr. Wong,0.0,0.0,0.0,1.0

In [34]:
# Feature building: 

def celltypelabel(x):
    if ((x['cell_size_uniformity'] > 5) & (x['cell_shape_uniformity'] > 5)):
        return('normal')
    else:
        return('abnormal')


combined_df['cell_type_label'] = combined_df.apply(lambda x: celltypelabel(x), axis=1)

In [35]:
combined_df[['patient_id', 'cell_type_label']]

     patient_id cell_type_label
0       1000025        abnormal
1       1002945        abnormal
2       1015425        abnormal
3       1016277          normal
4       1017023        abnormal
..          ...             ...
694      776715        abnormal
695      841769        abnormal
696      888820          normal
697      897471          normal
698      897471          normal

[698 rows x 2 columns]

In [36]:
combined_df[~(combined_df.cell_size_uniformity >5) & (combined_df.cell_shape_uniformity >5)]

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name,Dr. Doe,Dr. Lee,Dr. Smith,Dr. Wong,cell_type_label
15,1047630,7.0,4.0,6,4,6,1,4.0,3.0,1.0,1.0,Dr. Lee,0.0,1.0,0.0,0.0,abnormal
50,1108370,9.0,5.0,8,1,2,3,2.0,1.0,5.0,1.0,Dr. Smith,0.0,0.0,1.0,0.0,abnormal
52,1110102,10.0,3.0,6,2,3,5,4.0,10.0,2.0,1.0,Dr. Doe,1.0,0.0,0.0,0.0,abnormal
68,1120559,8.0,3.0,8,3,4,9,8.0,9.0,8.0,1.0,Dr. Wong,0.0,0.0,0.0,1.0,abnormal
84,1147699,3.0,5.0,7,8,8,9,7.0,10.0,7.0,1.0,Dr. Lee,0.0,1.0,0.0,0.0,abnormal
86,1148278,3.0,3.0,6,4,5,8,4.0,4.0,1.0,1.0,Dr. Smith,0.0,0.0,1.0,0.0,abnormal
99,1166630,7.0,5.0,6,10,5,10,7.0,9.0,4.0,1.0,Dr. Lee,0.0,1.0,0.0,0.0,abnormal
124,1175937,5.0,4.0,6,7,9,7,8.0,10.0,1.0,1.0,Dr. Smith,0.0,0.0,1.0,0.0,abnormal
186,1206695,1.0,5.0,8,6,5,8,7.0,10.0,1.0,1.0,Dr. Doe,1.0,0.0,0.0,0.0,abnormal
187,1206841,10.0,5.0,6,10,6,10,7.0,7.0,10.0,1.0,Dr. Wong,0.0,0.0,0.0,1.0,abnormal
191,1211202,7.0,5.0,10,10,10,10,4.0,10.0,3.0,1.0,Dr. Doe,1.0,0.0,0.0,0.0,abnormal
223,1226612,7.0,5.0,6,3,3,8,7.0,4.0,1.0,1.0,Dr. Smith,0.0,0.0,1.0,0.0,abnormal
226,1227481,10.0,5.0,7,4,4,10,8.0,9.0,1.0,1.0,Dr. Lee,0.0,1.0,0.0,0.0,abnormal
230,1230688,7.0,4.0,7,4,3,7,7.0,6.0,1.0,1.0,Dr. Lee,0.0,1.0,0.0,0.0,abnormal
232,1231706,8.0,4.0,6,3,3,1,4.0,3.0,1.0,0.0,Dr. Doe,1.0,0.0,0.0,0.0,abnormal
260,255644,10.0,5.0,8,10,3,10,5.0,1.0,3.0,1.0,Dr. Lee,0.0,1.0,0.0,0.0,abnormal
270,390840,8.0,4.0,7,1,3,10,3.0,9.0,2.0,1.0,Dr. Smith,0.0,0.0,1.0,0.0,abnormal
279,476903,10.0,5.0,7,3,3,7,3.0,3.0,8.0,1.0,Dr. Wong,0.0,0.0,0.0,1.0,abnormal
283,492268,10.0,4.0,6,1,2,10,5.0,3.0,1.0,1.0,Dr. Smith,0.0,0.0,1.0,0.0,abnormal
295,606722,5.0,5.0,7,8,6,10,7.0,4.0,1.0,1.0,Dr. Smith,0.0,0.0,1.0,0.0,abnormal
300,635844,8.0,4.0,10,5,4,4,7.0,10.0,1.0,1.0,Dr. Smith,0.0,0.0,1.0,0.0,abnormal
323,733823,5.0,4.0,6,10,2,10,4.0,1.0,1.0,1.0,Dr. Smith,0.0,0.0,1.0,0.0,abnormal
329,760239,10.0,4.0,6,4,5,10,7.0,1.0,1.0,1.0,Dr. Lee,0.0,1.0,0.0,0.0,abnormal
330,76389,10.0,4.0,7,2,2,8,6.0,1.0,1.0,1.0,Dr. Lee,0.0,1.0,0.0,0.0,abnormal
333,785208,5.0,4.0,6,6,4,10,4.0,3.0,1.0,1.0,Dr. Lee,0.0,1.0,0.0,0.0,abnormal
414,1238948,8.0,5.0,6,2,3,10,6.0,6.0,1.0,1.0,Dr. Doe,1.0,0.0,0.0,0.0,abnormal
426,1258556,5.0,3.0,6,1,2,1,1.0,1.0,1.0,0.0,Dr. Wong,0.0,0.0,0.0,1.0,abnormal
523,672113,7.0,5.0,6,10,4,10,5.0,3.0,1.0,1.0,Dr. Lee,0.0,1.0,0.0,0.0,abnormal
591,1295529,2.0,5.0,7,6,4,10,7.0,6.0,1.0,1.0,Dr. Doe,1.0,0.0,0.0,0.0,abnormal
603,1352663,5.0,4.0,6,8,4,1,8.0,10.0,1.0,1.0,Dr. Doe,1.0,0.0,0.0,0.0,abnormal
605,352431,10.0,5.0,10,3,5,8,7.0,8.0,3.0,1.0,Dr. Lee,0.0,1.0,0.0,0.0,abnormal